//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalizationStoreRemover.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalizationStoreRemover.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Archive All.
        /// </summary>
        internal static string Button_ArchiveAll {
            get {
                return ResourceManager.GetString("Button_ArchiveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete All.
        /// </summary>
        internal static string Button_DeleteAll {
            get {
                return ResourceManager.GetString("Button_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local / Remote.
        /// </summary>
        internal static string Button_LocalRemote {
            get {
                return ResourceManager.GetString("Button_LocalRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload.
        /// </summary>
        internal static string Button_Reload {
            get {
                return ResourceManager.GetString("Button_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        internal static string Button_Validate {
            get {
                return ResourceManager.GetString("Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Archive.
        /// </summary>
        internal static string Column_Archive {
            get {
                return ResourceManager.GetString("Column_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Column_Delete {
            get {
                return ResourceManager.GetString("Column_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Folder.
        /// </summary>
        internal static string Column_OpenFolder {
            get {
                return ResourceManager.GetString("Column_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        internal static string Column_User {
            get {
                return ResourceManager.GetString("Column_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remote computer&apos;s name is empty. Listing local files.
        /// </summary>
        internal static string Message_EmptyRemoteName {
            get {
                return ResourceManager.GetString("Message_EmptyRemoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during archiving.
        /// </summary>
        internal static string Message_ErrorDuringArchiving {
            get {
                return ResourceManager.GetString("Message_ErrorDuringArchiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during deleting.
        /// </summary>
        internal static string Message_ErrorDuringDeleting {
            get {
                return ResourceManager.GetString("Message_ErrorDuringDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during file listing.
        /// </summary>
        internal static string Message_ErrorDuringFileListing {
            get {
                return ResourceManager.GetString("Message_ErrorDuringFileListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during process start.
        /// </summary>
        internal static string Message_ErrorDuringProcessStart {
            get {
                return ResourceManager.GetString("Message_ErrorDuringProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File sucessfully archived.
        /// </summary>
        internal static string Message_FileSuccessfullyArchived {
            get {
                return ResourceManager.GetString("Message_FileSuccessfullyArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File successfully deleted.
        /// </summary>
        internal static string Message_FileSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("Message_FileSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folder to open.
        /// </summary>
        internal static string Message_FolderToOpen {
            get {
                return ResourceManager.GetString("Message_FolderToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Found {0} file(s).
        /// </summary>
        internal static string Message_FoundXFiles {
            get {
                return ResourceManager.GetString("Message_FoundXFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Listing local files.
        /// </summary>
        internal static string Message_ListingLocalFiles {
            get {
                return ResourceManager.GetString("Message_ListingLocalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Msg.
        /// </summary>
        internal static string Message_Message {
            get {
                return ResourceManager.GetString("Message_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No access to file.
        /// </summary>
        internal static string Message_NoAccessToFile {
            get {
                return ResourceManager.GetString("Message_NoAccessToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching personalization store files.
        /// </summary>
        internal static string Message_SearchingPersoStoreFiles {
            get {
                return ResourceManager.GetString("Message_SearchingPersoStoreFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trying to archive.
        /// </summary>
        internal static string Message_TryingToArchive {
            get {
                return ResourceManager.GetString("Message_TryingToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trying to delete.
        /// </summary>
        internal static string Message_TryingToDelete {
            get {
                return ResourceManager.GetString("Message_TryingToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local Computer.
        /// </summary>
        internal static string Radio_LocalComputer {
            get {
                return ResourceManager.GetString("Radio_LocalComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remote Computer.
        /// </summary>
        internal static string Radio_RemoteComputer {
            get {
                return ResourceManager.GetString("Radio_RemoteComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Computer :.
        /// </summary>
        internal static string StatusLabel_Computer {
            get {
                return ResourceManager.GetString("StatusLabel_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local.
        /// </summary>
        internal static string StatusLabel_Computer_Local {
            get {
                return ResourceManager.GetString("StatusLabel_Computer_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last reload :.
        /// </summary>
        internal static string StatusLabel_LastReload {
            get {
                return ResourceManager.GetString("StatusLabel_LastReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation time :.
        /// </summary>
        internal static string Text_CreationTime {
            get {
                return ResourceManager.GetString("Text_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last access time :.
        /// </summary>
        internal static string Text_LastAccessTime {
            get {
                return ResourceManager.GetString("Text_LastAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last modification time :.
        /// </summary>
        internal static string Text_LastModificationTime {
            get {
                return ResourceManager.GetString("Text_LastModificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must have access to the C$ share of the remote computer..
        /// </summary>
        internal static string Text_MessageCShare {
            get {
                return ResourceManager.GetString("Text_MessageCShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Computer Choice.
        /// </summary>
        internal static string Title_FrmComputerChoice {
            get {
                return ResourceManager.GetString("Title_FrmComputerChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NAV Personalization Store Remover.
        /// </summary>
        internal static string Title_FrmFileList {
            get {
                return ResourceManager.GetString("Title_FrmFileList", resourceCulture);
            }
        }
    }
}
